'use strict';

export const GET_WEATHER = 'GET_WEATHER';

export const ADD_LOCATION = 'ADD_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const USER_LOCATION = 'USER_LOCATION';
export const SEARCH_LOCATIONS = 'SEARCH_LOCATIONS';
